-- CREATE SCHEMA IF NOT EXISTS CUSTOMER_SCHEMA;

-- USE SCHEMA CUSTOMER_SCHEMA;

-- CREATE TABLE CUSTOMERS (
--   ID INT,
--   NAME VARCHAR,
--   EMAIL VARCHAR
-- );
# ----------------
CREATE TABLE ORDERS (
  ORDER_ID INT PRIMARY KEY,
  CUSTOMER_ID INT,
  AMOUNT DECIMAL(10,2),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_NUMBER)
);
