-- CREATE SCHEMA IF NOT EXISTS CUSTOMER_SCHEMA;

-- USE SCHEMA CUSTOMER_SCHEMA;

-- CREATE TABLE CUSTOMERS (
--   ID INT,
--   NAME VARCHAR,
--   EMAIL VARCHAR
-- );

CREATE TABLE CUSTOMERS (
  ID INT,
  NAME VARCHAR(100
  EMAIL VARCHAR(255)
);
