# Triggers the action based on branch and path.
on:
  push:
    branches:
      - dev
    paths:
      - './migrations/custom/**'

  workflow_dispatch:

jobs:
  schema-change-job:
    runs-on: ubuntu-latest

    steps:
      # Checking out the repository
      - name: Retrieve repository
        uses: actions/checkout@v2

      - name: Use Python 3.8
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Install schemachange
        run: |
          pip install schemachange
          # pip install snowflake-connector-python

      - name: Execute schemachange
        env:
          SNOWFLAKE_ACCOUNT: ${{secrets.SNOWFLAKE_ACCOUNT}}
          SNOWFLAKE_USERNAME: ${{secrets.SNOWFLAKE_USERNAME}}
          SNOWFLAKE_ROLE: ${{secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          
 
        run: |
          schemachange -f ./migrations/custom \
            -a $SNOWFLAKE_ACCOUNT \
            -u $SNOWFLAKE_USERNAME \
            -r $SNOWFLAKE_ROLE \
            -w $SNOWFLAKE_WAREHOUSE \
            -d $SNOWFLAKE_DATABASE \
            -c $SNOWFLAKE_DATABASE.SCHEMACHANGE.CHANGE_HISTORY \
            --create-change-history-table
